login_link = "//*[text()='Log in']"
email = "element-0"
password = "element-3"
login_btn = "//*[@data-gtm-id='start-email-login']"
add_task = "//button[text()='Add task']"
task_name = "//p[@data-placeholder='Task name']"
description = "//p[@data-placeholder='Description']"
add_task_btn = "//button[@aria-label='Add task']"
cancel_task_btn = "//button[@aria-label='Cancel']"
verify_task = "//div[text()='%s']"
mark_task_complete = "//button[@class='task_checkbox priority_1']"
add_sub_task = "//div[contains(@class, 'rhBN4zt')]/div[contains(@class, '_2a3b75a1')]/button[@type='button']"
close_modal = "//button[@aria-label='Close modal']"